name: Secrets Scan

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - master
      - dev
      - staging

jobs:
  secrets:
    name: Gitleaks
    uses: Kuru-Labs/.github/.github/workflows/gitleaks-reusable.yml@main
    with:
      fail-on-leak: true
    secrets: inherit
    permissions:
      contents: read
      pull-requests: write
